### PR TITLE
Update Whirlpool to 0.10.4

### PR DESCRIPTION
**Pull request by LightningSats**

### CODE REVIEW

**Comment by elkimek** [comment]
There's no .jar file yet tho :)

**Comment by Amiga500** [comment]
I prepared the same yesterday.. but seeing .jar missing and waiting for it too :D

**Comment by elkimek** [comment]
According to TDev 0.10.4 wasn't released and isn't ready yet.

**Comment by elkimek** [comment]
Nevermind lol. 1 minute later...https://github.com/Samourai-Wallet/whirlpool-client-cli/releases/tag/0.10.4

**Comment by elkimek** [comment]
Tested on Rock64, all good.

**Comment by Amiga500** [comment]
It works on RPI4 too.

**Comment by LightningSats** [comment]
Version 0.10.3 has a know issue, this should be updated ASAP

**Pull request merged**
