### PR TITLE
check type of disk installed (x86_64)

### PR DESCRIPTION
**Pull request by albercoin**
check the type of disk "SATA" (sda, sdb, ...) or "NVMe" (nvme0n1p1, nvme0n1p2, ...)

## Description
check the type of disk "SATA" (sda, sdb, ...) or "NVMe" (nvme0n1p1, nvme0n1p2, ...)

## Checklist

* [x] tested successfully on local MyNode, if yes, list the device(s) below
* [ ] mentioned related open issue, if any

## List of test device(s)
Tested in Debian 11.6 (amd64)

### CODE REVIEW

**Comment by tehelsper** [comment]
I think there needs to be a better way to check for SATA. Sometimes the OS drive, like on the Model 2, is actually sdb.

```
admin@myNode:~$ lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 931.5G  0 disk
└─sda1   8:1    0 931.5G  0 part /mnt/hdd
sdb      8:16   1  29.8G  0 disk
├─sdb1   8:17   1   512M  0 part /boot/efi
└─sdb2   8:18   1  29.3G  0 part /
admin@myNode:~$
```

You could check to see if the device is nvme, then check for p1 sort of like this code assumes.

https://github.com/mynodebtc/mynode/blob/202eb6c81c05ecde87275d83dab12872b7be8f53/rootfs/standard/usr/bin/mynode_startup.sh#L155

**Comment by albercoin** [comment]
ok.. i've changed the condition

>
      case "$X86_DEVICE" in
            sd* | hd* | vd*)
                # SATA
                X86_PARTITION_NUMBER=$(cat /proc/partitions | grep -c "${X86_DEVICE}[0-9]")
                ;;
            nvme*)
                # NVMe
                X86_PARTITION_NUMBER=$(cat /proc/partitions | grep -c "${X86_DEVICE}p[0-9]")
                ;;            
        esac
> 

and works fine.

i've tested in Debian 11.6 Virtual machine with SATA and other with NVMe and OK.
the file is update with the changes, i'm newbie in github and i dont know if its ok like this

here a screenshot tested and works fine with NVMe (sda is data disk and nvme disk system)
myNode - ejemplo nvme ok

**Review by tehelsper — APPROVED** [review]

**Comment by tehelsper** [comment]
Looks good. Thanks!

**Comment by tehelsper** [comment]
Looks like there is a conflict for some reason. Can you resolve and push up a new commit? Or I can manually apply the changes to master.

**Pull request merged**
