### PR TITLE
WARden implementation into MyNode

### PR DESCRIPTION
**Pull request by pxsocs**
## Description

This pull requests contains a working implementation of the WARden into MyNode. Some important notes:

### Installation / Upgrade
the script `warden_upgrade.sh` takes care of initial installation and upgrades. 
Instructions for an upgrade of current MyNode and upgrades can be found [here](https://github.com/pxsocs/warden_mynode/blob/production/WARDEN_README.md).
In short, the script downloads the latest version from the repository above which contains the required python files. 
At this point, the additional pip requirements not currently installed at MyNode are:
. Pandas
. python-dateutil
. simplejson
The installation script installs these.

### Architecture
In order to consume resources, it was opted to use the flask server already running for MyNode. WARden is implemented as a flask blueprint with one small modification to `mynode.py` file as below.

### mynode.py
Modified to include the flask blueprint and WARden metadata for app icons. Only required code here is:

Imports
```python
from warden.routes import warden
from warden.warden import warden_metadata
```

Blueprint
```python
app.register_blueprint(warden, url_prefix='/warden',
                       static_folder='static',
                       template_folder='templates',
                       static_url_path='warden/static')
```

### apps.html
Modified to include a new icon for the WARden. The javascript code checks for wallet activity to make a notification similar to the displayed below. 

Screen Shot 2020-10-10 at 2 07 47 PM

The code is below. Please note that it's checking if Specter is enabled as the WARden currently relies only on data from specter server.
```html
<!-- START WARDEN INCLUDE -->
    <div class="app_tile">
        <div class="app_status_icon {{ specter_status_color }}" id="warden_status_icon"></div>
        <div class="app_logo"><img class="app_logo_icon"
                src="{{url_for('static', filename='images/warden_square_logo.png')}}" />
        </div>
        <div class="app_title">the WARden</div>
        <div class="app_status" id="specter_status">{{ specter_status }}</div>
        <!-- App only runs when spected is enabled -->
        {% if specter_enabled %}
        <div class="app_contents">
            <a class="ui-button ui-widget ui-corner-all mynode_button" disabled href="/warden"
                id="warden_activity">Checking...</a>
            <a class="ui-button ui-widget ui-corner-all mynode_button" href="/warden" id="warden"
                target='_blank'>View</a>
        </div>
        {% else %}
        <div class="app_status" id="specter_status">Enable Specter to Run</div>
        {%endif%}
    </div>

    <!-- WARDEN CHECK FOR WALLET ACTIVITY -->
    <script>
        var currentLocation = window.location;
        var base_url = currentLocation.protocol + "//" + currentLocation.hostname + ":" + currentLocation.port
        $.getJSON(base_url + '/warden/check_activity', function (data) {
            // JSON result in `data` variable
            if (data == true) {
                $('#warden_activity').html("Wallet Activity Detected")
                $('#warden_activity').css("background-color", "DarkOrange");
                $('#warden_activity').css("color", "black");
            } else if (data == false) {
                $('#warden_activity').html("No Wallet Activity")
                $('#warden_activity').css("background-color", "darkgreen");
                $('#warden_activity').css("color", "white");
            }
        });
    </script>
    <!-- END WARDEN INCLUDE -->
```
### Blueprint 
The simplified directory structure is the following:
├── static  
│   └── images
├── templates
│   └── includes
└── warden
    ├── static
    │   ├── css
    │   ├── csv_files
    │   ├── dependencies
    │   │   ├── bootstrap
    │   │   ├── font-awesome
    │   │   ├── jquery
    │   │   ├── jquery-ui
    │   ├── images
    │   ├── js
    │   └── json_files
    └── templates
        └── warden

`/warden/routes.py` contains all the routes to access the pages
`/warden/warden_decorators.py` contains supporting decorators (mainly memoization)
`/warden/warden_pricing_engine.py` contains price requests 
`/warden/warden.py` contains the main methods for calculation returns and other supporting data

## Checklist

* [x] tested successfully on local MyNode, if yes, list the device(s) below
* [ ] mentioned related open issue, if any

## List of test device(s)

Raspi 4
Debian (VM)

## Issues
Issues can be reported at the [GitHub Repository](https://github.com/pxsocs/warden_mynode/issues).

### CODE REVIEW

**Comment by Amiga500** [comment]
Never hear about this portfolio and i like it

image

**Comment by richardsj** [comment]
Appears to be an excellent fit. Using a git submodule (from MyNodeBTC to include TheWarden) and putting the install steps inside the MyNoteBTC codebase would allow pinning of any given vetted/known version of TheWarden to be installed, rather than just grabbing it via wget.

In any case I support this merge.

**Comment by pxsocs** [comment]
WARden has now been refactored as a pip install (like Specter). 

```bash
pip3 install alphazeta.warden
```

Been trying to figure out how to deploy inside myNode scripts. Ideally launching as a service and using specter python 3 environment. 

More details and source code [here.](https://github.com/pxsocs/specter_warden)

**Comment by tlindi** [comment]
Shouldn't deployment be done from github release tar.gz same way as other apps are deployed now days?

And is warden project still live?

**Pull request closed without merging**
