### PR TITLE
Update application_info.json

### PR DESCRIPTION
**Pull request by SatoshiNakamotoBitcoin**

### CODE REVIEW

**Comment by tehelsper** [comment]
I think the new text is too long and would wrap. That text should not wrap.

**Comment by SatoshiNakamotoBitcoin** [comment]
Other apps like 

Manager Lightning Tool 

Have a more long text, maybe "Management" only, for PyBLØCK, is good idea too.

Thanks Taylor. 🙏

**Comment by tehelsper** [comment]
Yeah, that one is actually never displayed. It is too long as well. "Management" doesn't seem specific enough. I'm not really sure about any other ideas.

**Comment by SatoshiNakamotoBitcoin** [comment]
We think Dashboard is good too.

We updated the file. 

Thank you very much again Taylor.

**Comment by tehelsper** [comment]
OK, Dashboard is good.

**Comment by SatoshiNakamotoBitcoin** [comment]
Thank you very much.

**Pull request merged**
