### PR TITLE
Move documentation into separate `doc` directory and convert to markdown

### PR DESCRIPTION
**Pull request by MitchellCash**
Hopefully this helps as a start to eventually building out some more documentation for the project.

### CODE REVIEW

**Comment by abhiShandy** [comment]
We can add similar pages to the wiki

**Comment by MitchellCash** [comment]
@abhiShandy is that source code available somewhere?

Definitely can add similar pages to the wiki, but the canonical source of truth should probably still be this repo for this sort of documentation. Easier that way to have people update the documentation alongside their code changes. People might be less likely to update two different repos.

**Comment by abhiShandy** [comment]
I mean't github wiki: https://github.com/mynodebtc/mynode/wiki

**Comment by MitchellCash** [comment]
@abhiShandy ah apologies, it was a late night!

I have added these to the Wiki [here](https://github.com/mynodebtc/mynode/wiki) - check out the sidebar.

**Pull request merged**
