### PR TITLE
feat: add JAM

### PR DESCRIPTION
**Pull request by abhiShandy**
Installs JAM app (User Interface for Joinmarket)

## Checklist

* [ ] tested successfully on local MyNode, if yes, list the device(s) below
* [ ] mentioned related open issue, if any

### CODE REVIEW

**Comment by tehelsper** [comment]
I actually had been working on this over the past week and recently pushed up a branch.

https://github.com/mynodebtc/mynode/tree/jam

**Comment by abhiShandy** [comment]
let me know if you need help

**Comment by tehelsper** [comment]
Help testing would be awesome. I had to make some changes to things to get it working with the existing Joininbox backend.

Also, the new services wouldn't run with the Bitcoin wallet I'd been using, so I may need to have it remade with a legacy format. It had been using a new one.

**Comment by abhiShandy** [comment]
ok. I'll test your branch and let you know.

**Pull request closed without merging**
