### PR TITLE
[WIP] Watchtower page

### PR DESCRIPTION
**Pull request by abhiShandy**
So far, the watchtower page is only showing some static information: stats, policy, list of towers

TODO
- [ ] decode the tower pubkey correctly
- [x] Add tower dialog
- [x] Delete tower button
- [ ] Test with testnet

## Checklist

* [x] tested successfully on local MyNode, if yes, list the device(s) below
* [x] mentioned related open issue, if any

## List of test device(s)

Raspi4 64-bit, 4GB RAM

### CODE REVIEW

**Comment by abhiShandy** [comment]
I need help in decoding/encoding the pubkeys

**Comment by tehelsper** [comment]
I think they should always be in the format of "pubkey@address" and maybe just "pubkey" but the CLI command only suggests the former. You can probably also include a ":9911" or other port at the end of the address.

Basically, you should be able to copy in something like is shown under "WATCHTOWER SERVER URI" on the main LN page.

**Comment by abhiShandy** [comment]
Remove action of wtclient has caveats:
- if you provide just the pubkey, the tower isn't simply deactivated for future sessions
- if you provide both pubkey and address, it will remove the address from the list of addresses the tower unless it's the last one left
- the tower is never removed from the list of towers

**Comment by tehelsper** [comment]
@abhiShandy It sounds like these may be LND issues. Can you clarify if these issues are with the LND API?

**Pull request closed without merging**
