### PR TITLE
Refine overal visual styles

### PR DESCRIPTION
**Pull request by pedromvpg**
## Description

Proposal to remove thick overly rounded borders, add padding, reduce visual elements, and revise type hierarchy.

light@2x
dark@2x

### CODE REVIEW

**Comment by tehelsper** [comment]
This looks amazing! I've been thinking about a separate idea to show a bit more bitcoin / lnd info on the home page that would feel a lot cleaner with this new style.

This is very exciting. I will try it out in the next day or two.

**Comment by psychedelicbart** [comment]
looks amazing imo!

**Comment by Amiga500** [comment]
Fantastic Job! Please check into Lightning, Electrum Server and Tor, that on dark theme.. for the apps at the end of the page the background is white.

image

**Comment by Satosh1Nakamot0** [comment]
🕳🐇

**Review by tehelsper — APPROVED** [review]

**Comment by abhiShandy** [comment]
> Fantastic Job! Please check into Lightning, Electrum Server and Tor, that on dark theme.. for the apps at the end of the page the background is white. Is correct so?
> 
> image

I fixed this minor issue in #418

**Pull request merged**
