### PR TITLE
Reducing the length of settings page (using Bootstrap)

### PR DESCRIPTION
**Pull request by abhiShandy**
I am using the navigation tabs from Bootstrap to reduce the length of the settings page. I have used it just for the first settings block.

If you don't mind using Bootstrap and like the design, I'll apply it on other apps to further reduce the length.

Screen Shot 2020-02-19 at 11 43 35 PM

### CODE REVIEW

**Comment by abhiShandy** [comment]
I must say that using Bootstrap makes many small changes to the GUI, I have to either override them using CSS or implement bootstrap consistently everywhere.

For now, I have over-ridden any obvious changes using CSS.

However, I would like to gradually use more functionalities of Bootstrap to improve the UI/UX.

**Comment by Amiga500** [comment]
I installed your settings-gui branch, but settings aren't changed. There are other things to set?

**Comment by Amiga500** [comment]
I made some ideas here.. to discuss on..

In my opinion, it would be nice to have 

- all Settings into a page, without scrolling.. so using tabs for categories and subcategories. 
- for the main page.. all features in one page without scrolling it would be nice to have too
- why not have an option to hide/disabling/enabling almost all features of the main page (obviously not Bitcoin core (and LND maybe)). 
- In future user can choose for a minimalist installation (only Bitcoin Core and Settings on Main Page), custom installation, or all features.

**Comment by abhiShandy** [comment]
You have to refresh the page using Shift+F5 (or some other combo) to reload the page while ignoring cache.

**Comment by Amiga500** [comment]
Ok! I have clean all cache.. now password field is not perfectly centered:

image

Some comments of myNode tabs, if this new interface like to others too :)

- "Version" and "Change log" buttons are of difference size, font size and position. To standardize all.
- Maybe "Changelog" tab instead of "Change log"?
- Maybe Changelog tab without button inside and without repeated Change Log inside too? (every time you enter into that tab you'll see all list)
- Tab named "Change password", but into it the word is with capital P

Now that fields are compressed.. maybe use more spaces between lines?

**Comment by abhiShandy** [comment]
Yes, the aim is make the settings page smaller yet powerful. I plan to use tabs (or a side menu) to show a list of apps. On clicking on any app, it will show all the relevant options - status, reinstall, update, uninstall, disable, reset blockchain, etc

**Comment by abhiShandy** [comment]
> Ok! I have clean all cache.. now password field is not perfectly centered:
> 
> image
> 
> Some comments of myNode tabs, if this new interface like to others too :)
> 
> * "Version" and "Change log" buttons are of difference size, font size and position. To standardize all.
> * Maybe "Changelog" tab instead of "Change log"?
> * Maybe Changelog tab without button inside and without repeated Change Log inside too? (every time you enter into that tab you'll see all list)
> * Tab named "Change password", but into it the word is with capital P
> 
> Now that fields are compressed.. maybe use more spaces between lines?

Thanks for these suggestions. Improving the UI/UX involves tweaking many small things like these. I'll fix them.

**Comment by Amiga500** [comment]
Nice, i like these ideas! And as default to have either main page that settings page without scroller!

If you enlarge it with F11 have to be of the exact dimension of the screen. Now for example is little bigger! I don't know why.. first time i saw it

image

**Comment by abhiShandy** [comment]
I have improved the spacing between the fields in version and info tab, and made the lengthy changelog scrollable.

Screen Shot 2020-02-20 at 11 45 27 AM

**Comment by Amiga500** [comment]
> I have improved the spacing between the fields in version and info tab, and made the lengthy changelog scrollable.
> 
> Screen Shot 2020-02-20 at 11 45 27 AM

I like it a lot!!! Very very good!

**Comment by Amiga500** [comment]
Wow..

image

image

mmmhhh button check for updates put on other line with same size of the other one?

On firefox.. for Changelog i see the scrolling bar..

image

**Comment by Amiga500** [comment]
Ah.. i suggest to change the following :

Current Password
Password -------------------> New Password
Repeat Password -----------> Repeat New Password

**Comment by abhiShandy** [comment]
Regarding the version tab, I want to make it more minimalist.

1. Just show the current version (and hide the latest version) and any one of the below
2. If a new version is available and myNode is aware of it -> show the "update" button with latest available version
3. If a new version is not available or myNode is not aware of it -> show the "check for updates" button
4. If the last update failed -> show the "retry update" and "show error" button

**Comment by Amiga500** [comment]
On Status tab too, is present the scroll bar (firefox)

image

**Comment by tehelsper** [comment]
I like the idea a lot! I'd like to find a way to reduce the small CSS differences though.

Also, that section of info seems pretty critical to me, so I'd like to not require an extra tab click there. I'd like to see it applied to the logs and advanced settings. For logs, we could categorize them into something like myNode - core - apps or something. In advanced, I want to merge advanced and developer and put them in tabs and I want to add beta support in developer at some point.

**Comment by abhiShandy** [comment]
I'll take out the "info" and keep the rest.

Logs are pretty long now, I can either reduce their length or put it in a scrollable div, or both.

I'm using vanilla bootstrap now, but we can customize it's base variables to avoid doing minor CSS changes everywhere.

**Comment by Amiga500** [comment]
Good!

Some suggestion:

image

there isn't space between the yellow line and the phrase "This will change...". And this is for all tabs of the webpage. In my opinion it have to be same space that the one present at the end.

Then..

image

Why not use 2 or three colums to put all status, there is a lot of space unused (and not to use tabs in this case)

**Comment by abhiShandy** [comment]
I have reduced the number of clicks required to see a log, added tabs for each app and moved electrum server to core tab

@Amiga500 let me know what you feel

Screen Shot 2020-03-04 at 10 17 03 PM

**Comment by Amiga500** [comment]
Nice Job!

Some suggestion:

Settings -> myNode
1) Ok for Info space blocked.
2) For the tabs "Status", "Version", "Changelog", "Change Password", "Debug Log", "Dark Mode" and "Power" (check that i have fixed names of tabs too) i suggest to have for all tabs the same vertical space (for example use the same of "Change Log" tab), so dynamic and no static spaces. It would be nice if the scrollbar could be hide too, but obviously with functionality of scrolling that works.

Settings -> Service Status
1) in "Docker" tab is missing yellow space between two Docker status
2) Probably i'd like to have buttons to show logs, and to have the same vertical space:
myNode Startup Status (led status) (button to show)
QuickSync Status (led status) (button to show)
Tor Status (led status) (button to show)
3) I would use.. "Core Services", "Services", "Apps" (another sub tabs for apps) and "Others" or similar tab name.

Settings-> Advanced & Developer

1) "Reinstall Apps", "Beta Release", "Reset HTTP", "Uploader" and "Factory Reset"
2) Into Reinstall Apps, it would be nice to have the open of the choose field on top and not on down (if it's possible to choose the direction of the open) as this field is at the end of the webpage.

**Comment by tehelsper** [comment]
Hey, sorry about changing paths and I like the way this looks, but I'm now leaning towards breaking this into two pages now. What are your thoughts on moving the "status" type items like logs, etc... to a separate status page? I think that would also help with load times as well.

**Comment by abhiShandy** [comment]
Yes, I would like that. Settings page have too many things. Lets also consider moving the app-specific functionalities to their respective pages. For example, moving 'reset blockchain' to the bitcoin page as advanced operations at the bottom.

**Comment by tehelsper** [comment]
I agree somewhat, but I would like to keep the riskier options on the settings page so people don't inadvertently click them when trying random things. There is a tendency to click something out of curiosity, but less so on the settings page.

**Comment by abhiShandy** [comment]
since you have separated out the "status" from "settings" page, should I update this PR to use the tabs for the rest of the settings page?
I find the settings page too lengthy right now.

**Comment by abhiShandy** [comment]
I have update this PR to match the content of the current settings page in the tab-layout

**Comment by abhiShandy** [comment]
I think I should close this for now. I need to catch up with lot of new things on settings page.

**Pull request closed without merging**
