### PR TITLE
RTL v0.6.0

### PR DESCRIPTION
**Pull request by Amiga500**
WARNING!!!
tried on VM and RPI4.. but side bar is hide.. only if i refresh page it appears for a second and isn't possible to block it. I don't know if it's related to browser or what

### CODE REVIEW

**Comment by elkimek** [comment]
Need to change `/opt/mynode/RTL/RTL.conf` according to the release notes please see the: https://github.com/Ride-The-Lightning/RTL/releases

Tested, it fixes your issue.

**Comment by Amiga500** [comment]
> Need to change `/opt/mynode/RTL/RTL.conf` according to the release notes please see the: https://github.com/Ride-The-Lightning/RTL/releases
> 
> Tested, it fixes your issue.
> 
> Edit: Found it, this should do it #123

Very Good! I close mine :)

**Comment by Amiga500** [comment]
Close as #123 correct this

**Comment by Amiga500** [comment]
From this release the author added keys to verify the release.. maybe it can be helpful for Taylor to add it (like bitcoin core and lnd).
https://github.com/Ride-The-Lightning/RTL/releases

**Pull request closed without merging**
