### PR TITLE
Web interface for Samourai whirlpool

### PR DESCRIPTION
**Pull request by abhiShandy**
This for for setting up and running the remote Whirlpool CLI #37 

This should be merged after merging #76.

### CODE REVIEW

**Comment by abhiShandy** [comment]
Screen Shot 2019-11-24 at 12 04 57 PM
Screen Shot 2019-11-24 at 12 04 17 PM

**Comment by BTCxZelko** [comment]
Maybe a point to note, is that because we are only running with the --listen flag in the service file. In order to continue they need to install the GUI. This CLI is functioning as 24/7 mixing backend, but must be unlocked with the mobile passphrase. 

Potentially clear up some confusion.

**Comment by BTCxZelko** [comment]
So for the new install setup the process is the following:
1) Start Whirlpool.service
2) Install GUI 
3) Connect to remote-CLI type in http://mynode.local or myNode IP address
     Leave Port as is
4) Press Connect
5) Paste Pairing Payload from Mobile (instructions as before were good) into GUI
     Users should turn on Tor, however, the service flag should override even if they didn't via GUI
6) Restart whirlpool.service
7) Go to GUI, enter passphrase, control mixing via GUI

Maybe we make a note that anytime they make changes to configurations, the whirlpool.service must be restarted to take effect (a notice is made in the GUI as well)

**Comment by abhiShandy** [comment]
this has been merged with #76

**Pull request closed without merging**
