### PR TITLE
Bump LND to 0.9.2-beta

### PR DESCRIPTION
**Pull request by MitchellCash**

### CODE REVIEW

**Comment by Amiga500** [comment]
LND 0.9.1-beta has some crash at now. Waiting for an update from LND guys.

**Comment by MitchellCash** [comment]
@Amiga500 👍 thanks for letting me know

**Comment by Amiga500** [comment]
LND 0.9.2 is out

https://github.com/lightningnetwork/lnd/releases/tag/v0.9.2-beta

**Comment by Amiga500** [comment]
Trying to install 0.9.2 on top of latest commit build i have again on RPI4: E: Write error - ~LZMAFILE (28: No space left on device).

Attached logs!

[Write_error.txt](https://github.com/mynodebtc/mynode/files/4331664/Write_error.txt)

**Comment by MitchellCash** [comment]
Updated PR and commit for `lnd v0.9.2-beta`. Also rebased onto latest master and tested on RPi4 successfully.

@Amiga500 looks like your `log2ram` partition is full. I'd guess this would be the cause of the error. You might need to purge some old logs from `/var/log`.

**Comment by Amiga500** [comment]
> Updated PR and commit for `lnd v0.9.2-beta`. Also rebased onto latest master and tested on RPi4 successfully.
> 
> @Amiga500 looks like your `log2ram` partition is full. I'd guess this would be the cause of the error. You might need to purge some old logs from `/var/log`.

Yep.. upgrade script too at start delete all logs... very strange!

**Comment by tehelsper** [comment]
I upgraded to v0.9.2 as well and am getting stuck here on an RP4:

[INF] LTND: Waiting for chain backend to finish sync, start_height=621560

Has anyone else seen this?

**Comment by MitchellCash** [comment]
@tehelsper I didn't experience that. I am fully synced right now and when I first started node on `lnd v0.9.2-beta` the lnd backend sync operation completed in under a second (according to the logs)

**Comment by Amiga500** [comment]
> I upgraded to v0.9.2 as well and am getting stuck here on an RP4:
> 
> [INF] LTND: Waiting for chain backend to finish sync, start_height=621560
> 
> Has anyone else seen this?

I have reinstalled myNode from scratch (reformatted to 0.1.95 --> to my build with LND 0.9.2) and for now LND 0.9.2 is working fine. Only issues with Dojo but i'm reinstalling it (in past resolved always in this manner)

**Comment by tehelsper** [comment]
It works now. I saw others had seen similar issues when LND was connecting to bitcoin via localhost vs 127.0.0.1 so I updated that and things got better.

**Comment by Amiga500** [comment]
> It works now. I saw others had seen similar issues when LND was connecting to bitcoin via localhost vs 127.0.0.1 so I updated that and things got better.

Oh nice then.. however i confirm.. here LND ok.. and the other too. ;)

**Comment by Amiga500** [comment]
I installed your latest commit build.. LND rebooted :(

[LND 0.9.2 ISSUE.TXT](https://github.com/mynodebtc/mynode/files/4333355/LND.0.9.2.ISSUE.TXT)

I think that LND guys didn't resolve it. I have to contact them

**Comment by tehelsper** [comment]
That doesn't look problematic to me. It doesn't look like it crashed. Am I missing something? THe service did reboot, but it looks like systemd told it to.

**Comment by Amiga500** [comment]
well.. on lnd 0.9.1 i had multiple reboots.. here happened one time for now.. i have however opened lightningnetwork/lnd#4083, let see what they says

**Comment by Roasbeef** [comment]
lightningnetwork/lnd#4083 has been closed. In the logs they provided, it appears `lnd` was instructed to restart. No sign that we've had a regression related to the ARM assembly issue in `v0.9.1`.

**Pull request closed without merging**
